spring:
  profiles:
    active: local # 기본 구동 프로필을 local(H2 인메모리)로 지정하여 환경변수 없이 가동 가능하게 조치

  application:
    name: final

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
    try-it-out-enabled: true
